input = "packages/example_model/defaults.json"

[model]
spec = "example_model"
version = "0.0.1"

[runtime]
spec = "process"
command = "python"
args = [
  "-m",
  "example_model.cloud_mrp_executor",
]

[runtime.cloud]
keyvault = "cfa-predict"
local_image = "cfa-calibration-tools-example-model-python"
repository = "cfa-calibration-tools-example-model"
task_mrp_config_path = "/app/example_model.mrp.task.toml"
pool_prefix = "example-model-cloud"
job_prefix = "example-model-cloud"
input_container_prefix = "example-model-cloud-input"
output_container_prefix = "example-model-cloud-output"
logs_container_prefix = "example-model-cloud-logs"
input_mount_path = "/cloud-input"
output_mount_path = "/cloud-output"
logs_mount_path = "/cloud-logs"
vm_size = "large"
jobs_per_session = 1
task_slots_per_node = 50
pool_max_nodes = 5
task_timeout_minutes = 60
pool_ready_timeout_minutes = 20
pool_auto_scale_evaluation_interval_minutes = 5
dispatch_buffer = 1000
print_task_durations = false

[output]
spec = "filesystem"
dir = "./output"
