input = "defaults.json"

[model]
spec = "example_model"
version = "0.0.1"

[runtime]
spec = "inline"
callable = "example_model.example_model:run_inline"

[output]
spec = "filesystem"
dir = "./output"
